version: "3"

services:
  server:
    container_name: ITAU_SERVER_APP
    restart: always
    build: .
    ports:
      - "3000:3000"
      - "666:666"
    environment:
      CATS_API_KEY: '8834fa46-dad4-445a-907f-31fad12a77e4'
      MONGO_URL: 'mongodb://mongo:27017/itau',
      API_URL: 'https://api.thecatapi.com/v1',
      METRICS_PORT: 666
      LOGGLY_TOKEN: "b1d8592c-cf50-4cab-9373-1aee2b9e8162"
      LOGGLY_SUBDOMAIN: "ArchanjoJr"
    links:
      - mongo

  mongo:
    container_name: MONGODB
    image: 'mongo'
    ports:
      - "27017:27017"